#Элетрощит Мама
substitutions:
  board_name: 'power-meter-mk'
  static_ip: '192.168.0.17'
  number: '1'
  topic: "communal_payments/113/energy/esp_energy"
  topic_var: "communal_payments/113/energy/unaccounted/esp_energy"
  mk: '_mk'

globals:
  - id: delta
    type: float
    restore_value: no
    initial_value: '42000'

esphome:
  name: ${board_name}
  
esp32:
  board: esp32doit-devkit-v1

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  pzemac: !include packages/6pzem_energy.yaml
  #ble2: !include packages/44ble_tracker_113.yaml

wifi:
  reboot_timeout: 3min

uart:
  tx_pin: GPIO19
  rx_pin: GPIO18
  stop_bits: 2
  baud_rate: 9600
  
sensor:
  - platform: pzemac
    current:
      name: "MK PZEM Current"
    voltage:
      name: "MK PZEM Voltage"
    power:
      name: "MK PZEM Power"
      id: "pzem_power"
    frequency:
      name: "MK PZEM Frequency"
    power_factor:
      name: "MK PZEM Power Factor"
    update_interval: 30s