#В центральной возле роутера
substitutions:
  board_name: 'esp32-5-ant'
  static_ip: '192.168.0.161'
  number: '5'

esphome:
  name: ${board_name}
  platform: ESP32 
  board: esp-wrover-kit

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  ble: !include packages/4ble_tracker.yaml
  #miband: !include packages/5mi_band_battery.yaml