# 113 На кухне возле розетки
substitutions:
  board_name: 'esp32-12-ant'
  static_ip: '192.168.0.170'
  number: '12'
  
esphome:
  name: esp32-12-ant-miband
  
esp32:
  board: esp32dev

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  #ble: !include packages/4ble_tracker.yaml
  ble2: !include packages/44ble_tracker_113.yaml