# 113 за телевизором LG --> возле роутера
substitutions:
  board_name: 'esp32-19'
  static_ip: '192.168.0.168'
  number: '19'

esphome:
  name: ${board_name}
  platform: ESP32 
  board: esp-wrover-kit

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  ble2: !include packages/44ble_tracker_113.yaml