#В розетке окна в детской
substitutions:
  board_name: 'esp32-11-ant'
  static_ip: '192.168.0.178'
  number: '11'

esphome:
  name: esp32-11
  
esp32:
  board: esp32dev

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  ble: !include packages/4ble_tracker.yaml
  #am43: !include packages/7am43_cover.yaml