#В электрощитке
substitutions:
  board_name: 'esp32-10-ant'
  static_ip: '192.168.0.173'
  number: '10'

esphome:
  name: ${board_name}
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp32.yaml
  ble: !include packages/4ble_tracker.yaml