substitutions:
  board_name: 'invertor-battery'
  static_ip: '192.168.0.163'
  scan_duration: !secret scan_duration
  update_interval: !secret update_interval

esphome:
  name: ${board_name}
  
esp8266:
  board: nodemcuv2

globals:
  - id: last_power_change_time
    type: unsigned long
    restore_value: no
    initial_value: '0'

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml

sensor:
  - platform: adc
    pin: A0
    name: "Battery Pack VCC Internal"
    id: battery_pack_vcc_internal
    internal: True
    force_update: True 
    update_interval: 100ms
    filters:
      - multiply: 15.35
      - skip_initial: 10  # Задержка публикации данных после перезагрузки
      - median:
          window_size: 20    # Считаем медиану по последним 20 значениям
          send_every: 10     # Отправляем медианное значение каждые 10 новых
          send_first_at: 10  # Первое значение отправляется после 10 полученных данных
    accuracy_decimals: 2
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:car-battery

  - platform: template
    name: "Battery Pack VCC"
    id: battery_pack_vcc
    update_interval: 5s
    force_update: True
    lambda: |-
      return id(battery_pack_vcc_internal).state;
    filters:
      - skip_initial: 1  # Задержка публикации данных после перезагрузки
      - median:
          window_size: 5    # Считаем медиану по последним 5 значениям
          send_every: 1     # Отправляем медианное значение каждые 5 новых
    accuracy_decimals: 2
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:car-battery

  - platform: template
    name: "Battery Pack Level"
    id: battery_pack_level
    update_interval: 10s
    force_update: True
    device_class: "battery"
    state_class: "measurement"
    unit_of_measurement: '%'
    accuracy_decimals: 1
    icon: mdi:car-battery
    lambda: |-
      float voltage_measured = id(battery_pack_vcc_internal).state;
      unsigned long current_time = millis();
      
      // Проверяем, прошло ли 3 минуты с последнего изменения состояния питания
      if (current_time - id(last_power_change_time) < 180000) {
        return id(battery_pack_level).state;
      }
      
      if (!id(power_online_contact).state) {
        voltage_measured -= 0.9; // Компенсация при зарядке
      }
      
      if (voltage_measured >= 12.6) {
        return 100.0;
      } else if (voltage_measured > 11.4) {
        return ((voltage_measured - 11.4) / (12.6 - 11.4)) * 100.0;
      } else if (voltage_measured >= 11.0 && voltage_measured <= 11.4) {
        return 0.0;
      } else {
        return NAN;
      }
    filters:
      - skip_initial: 2
      - median:
          window_size: 10
          send_every: 1  

  - platform: pzemac
    current:
      name: "Invertor Current"
      id: "invertor_current"
      accuracy_decimals: 1
    voltage:
      name: "Invertor Voltage"
      id: "invertor_voltage"
      accuracy_decimals: 1
    power:
      name: "Invertor Power"
      id: "invertor_power"
      accuracy_decimals: 1
    frequency:
      name: "Invertor Frequency"
      accuracy_decimals: 1
    power_factor:
      name: "Invertor Power Factor"
      accuracy_decimals: 2
    update_interval: 15s

  - platform: template
    name: "Invertor Power Average"
    internal: True
    lambda: |-
      return id(invertor_power).state;
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 1
    unit_of_measurement: 'W'
    accuracy_decimals: 2

display:
  platform: tm1637
  clk_pin: D6
  dio_pin: D5
  update_interval: 200ms
  lambda: |-
    if (!isnan(id(battery_pack_vcc_internal).state)) {
      it.printf("%.2f", id(battery_pack_vcc_internal).state);
    }

binary_sensor:
  - platform: homeassistant
    name: "Power Online Contact"
    id: power_online_contact
    entity_id: binary_sensor.power_online_contact
    on_state:
      then:
        - lambda: |-
            id(last_power_change_time) = millis();  // Обновляем время последнего изменения питания

uart:
  tx_pin: D8
  rx_pin: D7
  stop_bits: 1
  baud_rate: 9600
