substitutions:
  board_name: 'alarm_panel_mk'
  static_ip: '192.168.0.172'
  scan_duration: !secret scan_duration
  update_interval: !secret update_interval

esphome:
  name: ${board_name}
  platform: ESP8266
  board: esp12e

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  #led: !include packages/3status_led_esp8266.yaml

wifi:
  reboot_timeout: 0s

switch:
  - platform: gpio
    pin: GPIO13
    restore_mode: ALWAYS_OFF
    id: ${board_name}_CH1
    name: ${board_name}_arm
    icon: "mdi:alarm-light"
    interlock: [alarm_panel_mk_CH2, alarm_panel_mk_CH3, alarm_panel_mk_CH4]
    on_turn_on:
    - delay: 750ms
    - switch.turn_off: ${board_name}_CH1

  - platform: gpio
    pin: GPIO12
    restore_mode: ALWAYS_OFF
    id: ${board_name}_CH2
    name: ${board_name}_disarm
    icon: "mdi:alarm-light-off"
    interlock: [alarm_panel_mk_CH1, alarm_panel_mk_CH3, alarm_panel_mk_CH4]
    on_turn_on:
    - delay: 750ms
    - switch.turn_off: ${board_name}_CH2
    
  - platform: gpio
    pin: GPIO14
    restore_mode: ALWAYS_OFF
    id: ${board_name}_CH3
    name: ${board_name}_home
    icon: "mdi:home"
    interlock: [alarm_panel_mk_CH1, alarm_panel_mk_CH2, alarm_panel_mk_CH4]
    on_turn_on:
    - delay: 750ms
    - switch.turn_off: ${board_name}_CH3
    
  - platform: gpio
    pin: GPIO16
    restore_mode: ALWAYS_OFF
    id: ${board_name}_CH4
    name: ${board_name}_sos
    icon: "mdi:lifebuoy"
    interlock: [alarm_panel_mk_CH1, alarm_panel_mk_CH2, alarm_panel_mk_CH3]
    on_turn_on:
    - delay: 750ms
    - switch.turn_off: ${board_name}_CH4