binary_sensor:
  - platform: ble_presence
    mac_address: ${mifit_alex}
    name: ${alex_ble} ${number}

sensor:
  - platform: ble_rssi
    mac_address: ${mifit_alex}
    name: ${alex_ble} ${number} RSSI
