binary_sensor:
  - platform: ble_presence
    mac_address: ${mifit_lila}
    name: ${lila_ble} ${number}

sensor:
  - platform: ble_rssi
    mac_address: ${mifit_lila}
    name: ${lila_ble} ${number} RSSI
