binary_sensor:
  - platform: ble_presence
    mac_address: ${mifit_ira}
    name: ${ira_ble} ${number}

sensor:
  - platform: ble_rssi
    mac_address: ${mifit_ira}
    name: ${ira_ble} ${number} RSSI
